apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plain-my-destination-cluster-01
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/gareji/argocd.git
    path: broadway-central/staging/my-destination-cluster-01/addons/extra-manifests
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - PruneLast=true
