apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberentes-apps
  namespace: argocd
  labels:
    layer: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/gareji/argocd.git
    path: broadway-central/staging
    targetRevision: main
    directory:
      include: '**/app-of-app.yaml'
      recurse: true
      jsonnet: {}
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - PruneLast=true