apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.2.0
    helm:
      values: |
        providers:
          kubernetesGateway:
            enabled: true
          kubernetesIngress:
            enabled: false
        service:
          type: LoadBalancer
        gateway:
          enabled: true
          name: traefik-gateway
          listeners:
            web:
              port: 8000
              protocol: HTTP
              namespacePolicy:
                from: All
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true