apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-addons-tech
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gareji/argocd.git
    path: 1111111111/my-tech-cluster-name
    targetRevision: main
    directory:
      include: '**/addons/*'
      recurse: true
      jsonnet: {}
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - PruneLast=true